<?php

function extranet_preprocess_views_view_invgrid(&$variables){
/*var_dump($variables);
exit;*/
}

/*function extranet_theme_suggestions_image_formatter_alter(array &$suggestions, array $variables){
	var_dump("Padmanabhann extranet_image_formatter_alter");
}*/

function extranet_preprocess(&$variables, $hook){
	if($hook == "image_formatter"){
		$q = $variables['item']->getEntity();
		$w = $variables['image'];
		$a = $q->id();
		$variables['node_url'] = base_path()."node/".$a ;
	}
}

/*function extranet_theme(){

}*/